"""
Short "what is this for" descriptions shown on the Django admin's app/model
index pages (both /admin/ and /admin/<app_label>/). Django admin has no
built-in per-model description on that page, so this patches
`admin.site.get_app_list` to attach one, and `templates/admin/app_list.html`
(overriding Django's own copy) renders it. Imported once from
`config/urls.py` — see the import there for why.

Keep this dict in sync with what's actually registered — a stale/missing
entry just means no description shows for that model, not an error.
"""

from django.contrib import admin

MODEL_DESCRIPTIONS = {
    # -- tenancy --------------------------------------------------------
    "tenancy.Tenant": "One row per CPG client (the actual business account) — name, status, billing contact.",
    "tenancy.TenantMembership": "Who has access to which tenant, and at what role. Starts as an invite (email only); links to a real User once they log in via SSO.",
    # -- accounts ---------------------------------------------------------
    "accounts.User": "The login identity (email-based). One person can belong to multiple tenants via TenantMembership.",
    "accounts.UserIdentity": "Links a User to a specific SSO login (Google or Microsoft) so returning logins are recognized.",
    "accounts.InternalOperator": "Our own ops/support staff — kept separate from tenant roles so internal access is never confused with client access.",
    # -- offers -------------------------------------------------------------
    "offers.TcbManufacturerLink": "A CPG's identity at The Coupon Bureau (their email domain, brand ID) — links a Tenant to their TCB account.",
    "offers.DistributionChannel": "Lookup table of ways a coupon can be distributed (GS1 barcode, Google Wallet, etc.) — rarely edited.",
    "offers.Offer": "An actual promotion/campaign — save value, purchase requirements, redemption window, TCB registration status.",
    # -- coupons ------------------------------------------------------------
    "coupons.CouponClip": "One issued coupon instance (what a consumer gets when they 'clip' an offer) — serialized barcode data, deposit/redemption status.",
    "coupons.CouponFetchCode": "A short-lived PIN covering a batch of clips, for redeeming without scanning a barcode (POS keypad / ecommerce checkout).",
    # -- tcb_integration ------------------------------------------------
    "tcb_integration.TcbSyncLog": "Audit trail of every call made to TCB (or the mock) — offer registration, deposits, and outcomes. Start here if a deposit/registration fails.",
    # -- reporting ------------------------------------------------------
    "reporting.ClipEvent": "Raw funnel telemetry (link opened, clip confirmed, etc.) — not populated yet; no consumer landing page exists.",
    "reporting.RedemptionEvent": "A redemption pulled back from TCB's audit feed, reconciled to a specific CouponClip.",
    "reporting.PromoReport": "A compiled end-of-campaign metrics snapshot per offer — not generated by anything yet.",
    # -- api --------------------------------------------------------------
    "api.ApiClient": "A CPG's OAuth2 client-credentials app, for their own scripts to pull offer/reporting data. Wraps an oauth2_provider Application.",
    # -- framework / infrastructure (not ours, but worth explaining) -----
    "auth.Group": "Django's built-in permission groups. Unused so far.",
    "sites.Site": "Django's 'sites' framework, required by allauth. One row, effectively just the domain name.",
    "socialaccount.SocialApp": "Where Google/Microsoft OAuth client ID + secret get entered once provisioned — the missing piece for real SSO login.",
    "socialaccount.SocialAccount": "Allauth's record of one linked social login — fills in automatically once someone logs in via SSO.",
    "socialaccount.SocialToken": "Allauth's stored OAuth token for a linked social login.",
    "account.EmailAddress": "Allauth's record of verified/primary emails per user.",
    "oauth2_provider.Application": "An OAuth2 client app — what api.ApiClient wraps for CPG programmatic access.",
    "oauth2_provider.AccessToken": "An issued OAuth2 access token — fills in once a CPG actually calls the API.",
    "oauth2_provider.Grant": "An in-progress OAuth2 authorization grant (short-lived, mid-flow).",
    "oauth2_provider.IDToken": "An OpenID Connect ID token issued alongside an access token.",
    "oauth2_provider.RefreshToken": "A token used to obtain a new access token without re-authenticating.",
}

_original_get_app_list = admin.site.get_app_list


def _get_app_list_with_descriptions(request, app_label=None):
    app_list = _original_get_app_list(request, app_label)
    for app in app_list:
        for model_dict in app["models"]:
            key = f"{model_dict['model']._meta.app_label}.{model_dict['object_name']}"
            description = MODEL_DESCRIPTIONS.get(key)
            if description:
                model_dict["description"] = description
    return app_list


admin.site.get_app_list = _get_app_list_with_descriptions
