# Generated by Django 6.1 on 2026-08-22 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_initial'),
        ('offers', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcbSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('deposit_offer', 'Deposit offer (MOF create/edit)'), ('deposit_serial_batch', 'Deposit serial batch'), ('pull_audit', 'Pull audit data'), ('create_fetch_code', 'Create fetch code')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_clip', models.ForeignKey(blank=True, help_text='Nullable — a batch deposit covers many clips; see TcbSyncLogClip for the full batch membership.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcb_sync_logs', to='coupons.couponclip')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcb_sync_logs', to='offers.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcb_sync_logs', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TcbSyncLogClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_bucket', models.CharField(blank=True, max_length=30)),
                ('coupon_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.couponclip')),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_outcomes', to='tcb_integration.tcbsynclog')),
            ],
        ),
        migrations.AddIndex(
            model_name='tcbsynclog',
            index=models.Index(fields=['status', 'next_retry_at'], name='tcb_integra_status_efaf03_idx'),
        ),
        migrations.AddConstraint(
            model_name='tcbsynclogclip',
            constraint=models.UniqueConstraint(fields=('sync_log', 'coupon_clip'), name='unique_sync_log_clip'),
        ),
    ]
