# Generated by Django 6.1 on 2026-08-22 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ownership_mode', models.CharField(choices=[('partner_managed', 'Partner managed'), ('client_managed', 'Client managed')], max_length=20)),
                ('coupon_format', models.CharField(choices=[('0', 'Digital'), ('1', 'Paper')], default='0', max_length=1)),
                ('coupon_funder_id', models.CharField(help_text='GS1 Company Prefix or GTIN, 6-12 digits', max_length=12)),
                ('offer_code', models.CharField(help_text='6-digit offer code, unique per funder', max_length=6)),
                ('base_gs1', models.CharField(help_text="The base AI(8112) data string TCB's MOF is keyed on — see gs1.data_string.build_base_data_string.", max_length=70, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('campaign_start_at', models.DateTimeField()),
                ('campaign_end_at', models.DateTimeField()),
                ('redemption_start_at', models.DateTimeField()),
                ('redemption_end_at', models.DateTimeField()),
                ('rolling_expiration', models.BooleanField(default=False)),
                ('rolling_expiration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('total_circulation', models.PositiveIntegerField(help_text='TCB-enforced cap — can be raised, never lowered below current deposit count.')),
                ('max_clips', models.PositiveIntegerField(help_text='Our own distribution cap; should be <= total_circulation.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_tcb_registration', 'Pending TCB registration'), ('locked', 'Locked'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('void', 'Void')], default='draft', max_length=30)),
                ('mof_snapshot', models.JSONField(blank=True, default=dict, help_text="Mirrors TCB's real MOF request-body fields: primary_purchase_save_value/requirements/req_code/gtins/eans, additional_purchase_rules_code, second_/third_purchase_*, save_value_code, applies_to_which_item, store_coupon.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OfferChannelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='offers.distributionchannel')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_configs', to='offers.offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='distribution_channels',
            field=models.ManyToManyField(related_name='offers', through='offers.OfferChannelConfig', to='offers.distributionchannel'),
        ),
        migrations.CreateModel(
            name='TcbManufacturerLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer_email_domain', models.CharField(max_length=255)),
                ('brand_id', models.CharField(blank=True, help_text="TCB's internal brand id, fetched via Get Manufacturer Brands. Brands are created by the manufacturer themselves — we can only read them.", max_length=64)),
                ('connection_status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcb_links', to='tenancy.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='tcb_manufacturer_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offers', to='offers.tcbmanufacturerlink'),
        ),
        migrations.AddConstraint(
            model_name='offerchannelconfig',
            constraint=models.UniqueConstraint(fields=('offer', 'channel'), name='unique_offer_channel'),
        ),
        migrations.AddConstraint(
            model_name='tcbmanufacturerlink',
            constraint=models.UniqueConstraint(fields=('tenant', 'manufacturer_email_domain'), name='unique_tenant_manufacturer_domain'),
        ),
    ]
