# Generated by Django 6.1 on 2026-08-22 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_initial'),
        ('offers', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_reports', to='offers.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_reports', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ClipEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('link_opened', 'Link opened'), ('clip_confirmed', 'Clip confirmed'), ('wallet_saved', 'Wallet saved'), ('barcode_viewed', 'Barcode viewed')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, help_text='Hashed, never raw IP.', max_length=128)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=512)),
                ('utm_source', models.CharField(blank=True, max_length=128)),
                ('utm_medium', models.CharField(blank=True, max_length=128)),
                ('utm_campaign', models.CharField(blank=True, max_length=128)),
                ('utm_content', models.CharField(blank=True, max_length=128)),
                ('geo_coarse', models.CharField(blank=True, help_text='City/region/country only.', max_length=128)),
                ('device_type', models.CharField(blank=True, max_length=32)),
                ('raw_context', models.JSONField(blank=True, default=dict)),
                ('coupon_clip', models.ForeignKey(blank=True, help_text='Nullable — e.g. a link_opened event can precede a confirmed clip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='coupons.couponclip')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_events', to='offers.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_events', to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'offer', 'event_type'], name='reporting_c_tenant__c023e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RedemptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tcb_transaction_ref', models.CharField(blank=True, max_length=128)),
                ('redeemed_at', models.DateTimeField()),
                ('retailer_info', models.JSONField(blank=True, default=dict)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('coupon_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_events', to='coupons.couponclip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_events', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coupon_clip',), name='unique_redemption_per_clip')],
            },
        ),
    ]
