# Generated by Django 6.1 on 2026-08-22 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serialized_gs1', models.CharField(blank=True, max_length=70)),
                ('serial_number', models.CharField(blank=True, help_text='Consumer-code portion only; must start with our TCB-issued serialization prefix if we generate it ourselves rather than TCB.', max_length=15)),
                ('state', models.CharField(choices=[('issued', 'Issued'), ('pending_deposit', 'Pending deposit'), ('deposited', 'Deposited'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('void', 'Void')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('deposited_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from_at', models.DateTimeField(blank=True, help_text='Returned per-item by the real deposit response.', null=True)),
                ('valid_till_at', models.DateTimeField(blank=True, null=True)),
                ('tcb_deposit_status', models.CharField(blank=True, max_length=20)),
                ('redeemed_at', models.DateTimeField(blank=True, help_text='Written ONLY by the TCB audit-sync job. Never set this from a consumer-facing view or endpoint.', null=True)),
                ('created_via', models.CharField(choices=[('qr_scan', 'QR scan'), ('direct_link', 'Direct link'), ('api', 'API')], default='qr_scan', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CouponFetchCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fetch_code', models.CharField(help_text='Format enforced by TCB itself (prefixed with our provider prefix).', max_length=32)),
                ('mode', models.CharField(choices=[('pos', 'Point of sale'), ('ecomm', 'Ecommerce')], default='pos', max_length=10)),
                ('valid_till_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
