# Generated by Django 6.1 on 2026-08-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('offers', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponclip',
            name='distribution_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='offers.distributionchannel'),
        ),
        migrations.AddField(
            model_name='couponclip',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clips', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='couponclip',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='couponfetchcode',
            name='clips',
            field=models.ManyToManyField(related_name='fetch_codes', to='coupons.couponclip'),
        ),
        migrations.AddField(
            model_name='couponfetchcode',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_codes', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='couponclip',
            index=models.Index(fields=['tenant', 'state'], name='coupons_cou_tenant__193a92_idx'),
        ),
        migrations.AddIndex(
            model_name='couponclip',
            index=models.Index(fields=['offer'], name='coupons_cou_offer_i_9c9a61_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponclip',
            constraint=models.UniqueConstraint(condition=models.Q(('serialized_gs1__gt', '')), fields=('serialized_gs1',), name='unique_serialized_gs1'),
        ),
    ]
