# Generated by Django 6.1 on 2026-08-22 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended')], default='onboarding', max_length=20)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(help_text='Set at invite time; membership attaches to `user` once that email completes SSO login. See accounts.adapters.InviteOnlySocialAccountAdapter.', max_length=254)),
                ('role', models.CharField(choices=[('tenant_admin', 'Tenant Admin'), ('tenant_editor', 'Tenant Editor'), ('tenant_viewer', 'Tenant Viewer')], default='tenant_viewer', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked')], default='invited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Null until the invited_email completes SSO login and the invite is accepted — see accounts.adapters.InviteOnlySocialAccountAdapter.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_user'), models.UniqueConstraint(fields=('tenant', 'invited_email'), name='unique_tenant_invited_email')],
            },
        ),
    ]
